# Connection à la base de donnée

database_type: "sqlite" # mysql ou sqlite
sql:
  host: "localhost"
  database: "database_name"
  user: "username"
  password: "password"
  port: 3306

sqlite:
  file: "StelyMarket.db"


# Préfixe des regions lors de leurs création
region_prefix: "market_" # automatiquement suivi par un chiffre 

# Prix par défaut d'un market
default_price: 5000

# Préfixe à écrire sur la pancarte pour la relier à un market
create_sign_prefix: "[stelymarket]"

# Préfixe qui sera écris une fois la pancarte reliée à un market
# %prefix% = préfixe de la pancarte
linked_sign_prefix: "§7[§5StelyMarket§7]"

# Texte une fois la pancarte reliée à un market
linked_sign:
  - "%prefix%"
  - "§aPrix : §e%price%"
  - "§aFin : §e%end%"
  - "§7A louer"

# Texte sur la pancarte une fois qu'un market à été loué
buyed_market_sign:
  - "%prefix%"
  - "§aPrix : §e%price%"
  - "§aFin : §e%end%"
  - "§2Loué : %player%"

# Types de pancartes autorisés
allowed_signs:
  - "OAK_WALL_SIGN"
  - "OAK_SIGN"
  - "BIRCH_WALL_SIGN"
  - "BIRCH_SIGN"
  - "SPRUCE_WALL_SIGN"
  - "SPRUCE_SIGN"
  - "DARK_OAK_WALL_SIGN"
  - "DARK_OAK_SIGN"
  - "ACACIA_WALL_SIGN"
  - "ACACIA_SIGN"
  - "JUNGLE_WALL_SIGN"
  - "JUNGLE_SIGN"
  - "CRIMSON_WALL_SIGN"
  - "CRIMSON_SIGN"
  - "WARPED_WALL_SIGN"
  - "WARPED_SIGN"
  - "MANGROVE_WALL_SIGN"
  - "MANGROVE_SIGN"
